### PR TITLE
Feature/mqtt save fix

### LINKED ISSUE #405: MQTT `save` command and USB settings conflict with oneanother
If the user uses the `save` MQTT command, it writes data to EEPROM. Flash settings currently override these, so the save is essentially ignored if anything exists in flash.

### PR DESCRIPTION
**Pull request by ryan-summers**
Fixes #405 by updating the MQTT `save` command to save to internal flash instead of channel EEPROM.

We likely want to merge https://github.com/quartiq/minireq/pull/20 first.

### CODE REVIEW

File: src/net/mqtt_control.rs [hunk 1]
```diff
@@ -249,5 +265,30 @@ pub fn save_settings(
 
     channel.context_mut().save_configuration();
 
+    let settings = channel.context().settings();
+
+    let mut buf = [0u8; 256];
+    for (ch_indices, _) in ChannelSettings::iter_indices() {
```
Comment (ryan-summers) [inline src/net/mqtt_control.rs:271]: @jordens This is all very hacky currently, but I'm struggling to figure out how to do the following:
1. Get a partial path to `booster.channel[x]`
2. Iterate over the paths within `booster.channel[x]`
3. Combine (1) and (2) to save the final path to settings

I _think_ all of this code roughly does this, but it's not immediately clear. I would have expected that Miniconf would give me something like:
`booster.channels[x].path_to::<BoosterSettings>()` or similar. Any ideas here?

Comment (jordens) [reply src/net/mqtt_control.rs:271]: 1. Partial key lookup (path to indices) should be working (You'll get `TooShort(depth)`)
2. Subtree iteration in miniconf is https://github.com/quartiq/miniconf/issues/132
It's pretty clear and natural to do that there. It's a bit of work but sounds like it'll slot in just fine.
3. Rejoice

I don't see how `Tree::path_to::<T>()` would work. What if there are multiple `T` fields?

Comment (jordens) [reply src/net/mqtt_control.rs:271]: I'm fine with hardcoding `/booster/channel/<x>` for `save <x>` here.

File: src/main.rs [hunk 2]
```diff
@@ -287,12 +286,24 @@ mod app {
...
+                        "save" => {
+                            (&mut c.shared.main_bus, &mut c.shared.usb_terminal).lock(|bus, usb| {
+                                crate::net::mqtt_control::save_settings_to_flash(
+                                    bus,
+                                    usb.platform_mut(),
+                                    data,
+                                )
+                            })
+                        }
+                        _ => unreachable!(),
```
Comment (jordens) [inline src/main.rs:306]: It would be really cool to define the minireq handlers like in https://github.com/rust-embedded-community/menu

**Review by jordens — APPROVED** [review]

File: src/main.rs (hunk 2 above)
Comment (ryan-summers) [reply src/main.rs:306]: The main issue is that the function signature of a handler is inconsistent, so we can't defined compile-time storage for them anywhere.

Comment (jordens) [reply src/main.rs:306]: Same for the `menu` handlers. They get a context to call into.

Comment (ryan-summers) [reply src/main.rs:306]: Yeah, but the problem with a Context is that it can't have anonymous lifetime borrows in it. We got around this by borrowing the context itself, but that doesn't work if you need _two_ lockable items
